### ISSUE TITLE
JSON acceptance tests are failing

### ISSUE THREAD

**Issue by nhinds** [Yelp/puppet-uchiwa#33]
Running `rake beaker` shows 2 failing tests:

````
Failures:

  1) sensu class uchiwa ensure => present should produce consistent uchiwa.json file
     On host ``
     Failure/Error: expect(cat.stdout).to eq (uchiwa_json)
       
       
       expected: "{\n\"sensu\": [\n    {\n      \"name\": \"Main Server\",\n      \"host\": \"127.0.0.1\",\n      \"ssl\": false,\n      \"insecure\": false,\n      \"port\": 4567,\n      \"user\": \"sensu\",\n      \"pass\": \"secret\",\n      \"path\": \"\",\n      \"timeout\": 5000\n    }\n  ],\n  \"uchiwa\": {\n    \"host\": \"0.0.0.0\",\n    \"port\": 3000,\n    \"user\": \"\",\n    \"pass\": \"\",\n    \"stats\": 10,\n    \"refresh\": 10000\n  }\n}\n"
            got: "{\n\"sensu\": [\n    {\n      \"name\": \"Main Server\",\n      \"host\": \"127.0.0.1\",\n      \"ssl\": false,\n      \"insecure\": false,\n      \"port\": 4567,\n      \"user\": \"sensu\",\n      \"pass\": \"secret\",\n      \"path\": \"\",\n      \"timeout\": 5000\n    }\n  ],\n  \"uchiwa\": {\n    \"host\": \"0.0.0.0\",\n    \"port\": 3000,\n    \"user\": \"\",\n    \"pass\": \"\",\n    \"refresh\": 5\n  }\n}\n"
       
       (compared using ==)
       
       Diff:
       @@ -17,8 +17,7 @@
            "port": 3000,
            "user": "",
            "pass": "",
       -    "stats": 10,
       -    "refresh": 10000
       +    "refresh": 5
          }
        }
     # ./spec/acceptance/class_spec.rb:62:in `block (5 levels) in <top (required)>'
     # ./spec/acceptance/class_spec.rb:61:in `block (4 levels) in <top (required)>'

  2) sensu class uchiwa ensure => present should produce a uchiwa.json file from defaults
     On host ``
     Failure/Error: expect(cat.stdout).to eq (uchiwa_json)
       
       
       expected: "{\n\"sensu\": [\n    {\n      \"name\": \"sensu\",\n      \"host\": \"127.0.0.1\",\n      \"ssl\": false,\n      \"insecure\": false,\n      \"port\": 4567,\n      \"user\": \"sensu\",\n      \"pass\": \"sensu\",\n      \"path\": \"\",\n      \"timeout\": 5000\n    }\n  ],\n  \"uchiwa\": {\n    \"host\": \"0.0.0.0\",\n    \"port\": 3000,\n    \"user\": \"\",\n    \"pass\": \"\",\n    \"stats\": 10,\n    \"refresh\": 10000\n  }\n}\n"
            got: "{\n\"sensu\": [\n    {\n      \"name\": \"sensu\",\n      \"host\": \"127.0.0.1\",\n      \"ssl\": false,\n      \"insecure\": false,\n      \"port\": 4567,\n      \"user\": \"sensu\",\n      \"pass\": \"sensu\",\n      \"path\": \"\",\n      \"timeout\": 5\n    }\n  ],\n  \"uchiwa\": {\n    \"host\": \"0.0.0.0\",\n    \"port\": 3000,\n    \"user\": \"\",\n    \"pass\": \"\",\n    \"refresh\": 5\n  }\n}\n"
       
       (compared using ==)
       
       Diff:
       @@ -9,7 +9,7 @@
              "user": "sensu",
              "pass": "sensu",
              "path": "",
       -      "timeout": 5000
       +      "timeout": 5
            }
          ],
          "uchiwa": {
       @@ -17,8 +17,7 @@
            "port": 3000,
            "user": "",
            "pass": "",
       -    "stats": 10,
       -    "refresh": 10000
       +    "refresh": 5
          }
        }
     # ./spec/acceptance/class_spec.rb:81:in `block (5 levels) in <top (required)>'
     # ./spec/acceptance/class_spec.rb:80:in `block (4 levels) in <top (required)>'

Finished in 3 minutes 1 second
5 examples, 2 failures

Failed examples:

rspec ./spec/acceptance/class_spec.rb:57 # sensu class uchiwa ensure => present should produce consistent uchiwa.json file
rspec ./spec/acceptance/class_spec.rb:76 # sensu class uchiwa ensure => present should produce a uchiwa.json file from defaults
````

**Comment by solarkennedy** [comment]
Hmm. Looks a bit over-specified?
